apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: services
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: notification-config
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: MONGO_URI

