apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: database
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4=          # admin
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQxMjM=  # password123
