apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: services
  labels:
    app: auth-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
        - name: auth-service
          image: auth-service:v1
          imagePullPolicy: Never

          ports:
            - containerPort: 3001

          envFrom:
            - configMapRef:
                name: auth-config

          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: MONGO_URI

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET
