apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: services
data:
  PORT: "3002"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3003"
